### ISSUE TITLE
 - `21.0.68` `SpawnPlacementRegisterEvent` -> `RegisterSpawnPlacementsEvent` (#1154)

### ISSUE THREAD

**Issue by ootwclyhe** [baguchan/BagusLib#10]
- Bagus Lib (bagus_lib) has failed to load correctly
          java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/SpawnPlacementRegisterEvent
        - BagusMob (bagusmob) has failed to load correctly
          java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/SpawnPlacementRegisterEvent

**Comment by ootwclyhe** [comment]
also in EnchantWithMob

**Comment by baguchi** [comment]
have you tried newer version neoforge and new Bagus Lib and new EnchantWithMob?
and bagus mob is not yet update it for newer neoforge

**Comment by ootwclyhe** [comment]
server was successfully started
