### ISSUE TITLE
Client Disconnect in reason of render Thread after updating to latest version

### ISSUE THREAD

**Issue by shinei01** [baguchan/BagusLib#13]
Since the updates of 21/07 i get disconnected on client side in reason of a render thread.

On Version 1.20.1-5.1.0 it's working.

Attached is the latest debuglog

[debug.log](https://github.com/user-attachments/files/16331667/debug.log)

**Comment by baguchi** [comment]
thanks for bug reporting!
try this build and try again
https://modrinth.com/mod/bagus-lib/version/1.20.1-5.2.1

**Comment by baguchi** [comment]
or... If cannot solved
try open the bloomingnature's github's issues. It seem HierarchicalModel's root method is null

**Comment by shinei01** [comment]
it's working, thx
