### ISSUE TITLE
Bagus lib crashing with mahou tsukai

### ISSUE THREAD

**Issue by ShyviaAngel** [baguchan/BagusLib#14]
When rendering in mahou tsukai familiar it instantly hard to desktop and theyre no issues when removing the mod
[crash-2024-08-24_20.04.47-client.txt](https://github.com/user-attachments/files/16740447/crash-2024-08-24_20.04.47-client.txt)
[crash-2024-08-24_19.55.30-client.txt](https://github.com/user-attachments/files/16740448/crash-2024-08-24_19.55.30-client.txt)
 And be it single player or multiplayer
Tho at the very least in single player it rollback to the moment before

**Comment by baguchi** [comment]
fixed in 13.0.2!
