### ISSUE TITLE
hotfix for 1.20.1 crashes my game

### ISSUE THREAD

**Issue by baeZipster** [baguchan/BagusLib#5]
my latest.log mentions it failed to load your mixin from bagus-lib 

[latest.log](https://github.com/baguchan/BagusLib/files/13514379/latest.log) the 200th line of the log

**Comment by baeZipster** [comment]
[latest.log](https://github.com/baguchan/BagusLib/files/13517975/latest.log)
tested it with no other mods but the API mod, crash
1.20.1, neoforge version 47.1.79

**Comment by baguchi** [comment]
alright. I fixed in 1.20.1-4.1.1!
