### ISSUE TITLE
Crash on latest 1.20.4 Neoforge version

### ISSUE THREAD

**Issue by ModernGamingWorld** [baguchan/BagusLib#7]
![2023-12-16_21 28 19](https://github.com/baguchan/BagusLib/assets/75923060/23d3bbe0-5a51-4ac8-bb64-e3a8e1c05553)

**Comment by baguchi** [comment]
have you tried use bagusLib in neoforge 40.4.40 or above?

**Comment by ModernGamingWorld** [comment]
@baguchan Curseforge launcher has not added support for the new version on the Launcher, if thats the case put a disclaimer on the update or message Curseforge

**Comment by baguchi** [comment]
yeah... let's me write my discord

**Comment by ModernGamingWorld** [comment]
@baguchan I have just request Curseforge to push the new versions of Neoforge to the Launcher, so hopefully that will happen soon
